name: fastinationapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  line_icons: ^2.0.3
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
